### ISSUE TITLE
onde curriculo deve ficar?

### ISSUE THREAD

**Issue by H1d3l** [leonfers/App-Jobs#1]
o leoncio disse q deve ficar em concorrente e não em pessoa.

**Comment by H1d3l** [comment]
Concorrente é uma pessoa q tem um curriculo. Então curriculo deve ficar em pessoa e não em concorrente.

**Comment by leonfers** [comment]
opa
mandei no outro 

Bem o curriculo voce so manda quando esta concorrendo a uma vaga , e para cada vaga que vc esta concorrendo vc poderia mandar um curriculum diferente , assim fica melhor por em concorrente que e o relacionamento entre vaga e pessoa

**Comment by H1d3l** [comment]
blz.
