### ISSUE TITLE
Corrigir Diagrama de Classes

### ISSUE THREAD

**Issue by leonfers** [leonfers/App-Jobs#2]
Ta bacana o diagrama, so coloca as classes que tem outras classes com uma linha saindo da parte debaixo e indo para a parte de cima da outra classes.

**Comment by H1d3l** [comment]
é faz sentido mudar pra concorrente. Vou dar uma olhada no diagrama.

**Comment by H1d3l** [comment]
Não ficou muito claro. Quais classes devo mexer?

**Comment by leonfers** [comment]
as que vc botou a linha saindo do lado , coloca sempre saindo de baixo de uma para a parte de cima da outra , so se vc quiser , vc escreveu dentro entao nao deve ter problema

**Comment by H1d3l** [comment]
Fiz a atualização do diagrama.
